# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Solution.create([{name: 'Mentoring CT ®', description: 'O Mentoring CT® é a solução ideal para a construção ou o aprimoramento de Mecanismos de Integridade e Compliance, com a relação ‘custo x benefício’ altamente favorável a sua empresa. A metodologia utiliza consultoria assistida e colaborativa, possibilitando uma implementação rápida, eficiente, profissional e abrangendo todos os requisitos das leis anticorrupção.
', name_path: 'mentoring'}, 
                 {name:'Suply Chain Integrity', description: 'Modelo inovador e inédito que propicia a sua empresa o pleno atendimento aos requisitos da Lei 12.846/13 relativos a terceiros. O SCI assegura a implementação de Mecanismos de Integridade na sua cadeia de fornecedores com custos extremamente acessíveis a eles, sem demandar recursos de tempo e financeiros da empresa contratante.
                 ', name_path: 'suply'}, 
                 {name: 'Consultoria Especializada', description: 'Profissionais experientes e altamente qualificados atendem às necessidades das empresas nos mais variados assuntos relativos a Compliance, incluindo Risk Assessment, Due Diligences, avaliação da efetividade dos Mecanismos de Integridade, elaboração e revisão de políticas e procedimentos, implementação de parte ou do Mecanismo de Integridade completo, entre outros.
                  ', name_path: 'consultoria_especializada'}, 
                 {name: 'Soluções em Comunicação', description: 'Implementar ou manter um Mecanismo de Integridade efetivo demanda uma comunicação profissional, para assegurar sensibilização e conscientização dos diversos públicos na empresa, com regularidade. A Compliance 360º oferece um plano de comunicação completo e disponibiliza diversas soluções customizáveis, prontas para aplicação imediata. Desenvolve também peças especiais sob demanda.
                 ', name_path: 'solucoes_comunicacao'},
                 {name: 'Soluções em Treinamentos', description: 'Especialistas ministram treinamentos presenciais relativos a Compliance e/ou preparam treinamentos via Web (EAD), com utilização de ferramentas próprias para essa finalidade. Escopo, conteúdos e linguagem são customizáveis, conforme a necessidade de cada cliente. Certificados personalizados são fornecidos para todos os treinamentos.
                 ', name_path: 'solucoes_treinamentos'},
                 {name: 'Soluções em Gestão', description: 'Profissionais com ampla experiência em gestão de Mecanismos de Integridade e Compliance podem auxiliar a sua empresa a maximizar os resultados e a efetividade de seus processos. São oferecidos “Coaching” para os Compliance Officers, coordenação de Comitês, abordagem direta nos Conselhos de Administração e Diretoria, entre outros serviços.
                 ', name_path: 'solucoes_gestao'},
                 {name: 'Tecnologia de Compliance', description: 'A Compliance 360º oferece ferramentas inovadoras e de grande importância para apoiar a sua empresa na padronização e agilização de determinados processos de Compliance, tais como, gestão de terceiros, proibição de retaliação, realização de auditorias internas, etc.
                 ', name_path: 'tecnologia_compliance'},
                 {name: 'Canal de Denúncias', description: 'O Canal de Denúncias consiste num elemento essencial para assegurar efetividade do Mecanismo de Integridade e Compliance. Visando garantir a melhor solução para os nossos clientes, oferecemos o Canal de Ética – Contato Seguro: confidencialidade, 24h/7dias na semana, atendimento 100% por psicólogas, total segurança na proteção dos dados, triagem das alegações, relatórios gerenciais, avaliação legal, etc.
                  ', name_path: 'canal_denuncias'}])


ProductConsult.create!([{name: 'Avaliação de Riscos e Compliance', description: 'Processo estruturado para a identificação dos riscos de Compliance (fraude, corrupção, questões concorrenciais e antitruste, privacidade de dados, lavagem de dinheiro, conflito de interesses, relacionamento com terceiros e outros pertinentes ao tema) e estabelecimento de medidas mitigadoras. Inclui a classificação dos riscos, considerando aspectos relativos a impacto e probabilidade, mais uma proposta de plano de ação e forma de acompanhamento de implementação de tais medidas.', name_path: 'avaliacao_risco_compliance'},
{name: 'Apoio à Alta Direção', description: 'Plano de ação para a Alta Direção demonstrar engajamento e apoio (evidente e efetivo) às iniciativas a serem adotadas pela empresa, quanto à difusão do seu Mecanismo de Integridade e Sistema de Compliance, tanto dentro da organização, como também perante os terceiros com quem interage, atendendo, assim, os mecanismos de proteção esperados pelas legislações anticorrupção e aumentando a cultura da integridade.', name_path: 'apoio_a_alta_direcao'},
{name: 'Documentação de Compliance', description: 'Profissionais da Compliance 360º, com comprovada experiência no tema, avaliam a documentação existente, propõe eventuais alterações e elaboram os POPs (Procedimentos Operacionais Padrão), que porventura estejam faltando. Apresentam uma sugestão de estruturação inteligente dos documentos, incluindo Código de Conduta, Políticas, Procedimentos e demais Instruções Normativas. Esse serviço pode conter o desenho de processos de Compliance e a definição de controles que assegurem a sua efetividade, incluindo os registros pertinentes, com a finalidade de demonstrar o completo cumprimento dos requisitos e a existência de um mecanismo robusto de integridade e Compliance.', name_path: 'documentacao_de_compliance'},
{name: 'Processos e Controles', description: 'Para possibilitar o pleno atendimento, por parte dos funcionários e terceiros, do Código de Conduta e demais requisitos de um Mecanismo de Integridade, é necessária a existência de processos claros e ferramentas adequadas, perfeitamente implementados e comunicados.', name_path: 'processos_e_controles'},
{name: 'Comunicação', description: 'A Comunicação consiste em um dos pilares de sustentação para um Mecanismo de Integridade efetivo, tanto na fase de implementação quanto na de manutenção. Por isso, as legislações nacionais e internacionais dão especial ênfase a esse tópico e a Compliance 360º ajudará a sua empresa a estabelecer uma comunicação adequada, eficiente e eficaz.', name_path: 'comunicacao'},
{name: 'Treinamentos em Compliance', description: 'Instruir, qualificar e treinar as pessoas consiste em condição obrigatória para a formação de profissionais aptos para o exercício de suas funções. Da mesma maneira, para o Compliance, os treinamentos cumprirão tal papel e, juntamente com a comunicação regular, esclarecerão os riscos à empresa e aos funcionários, propiciando a estes a opção de fazer a “escolha certa”, tanto em relação a suas atitudes, quanto na realização dos processos e consecução dos negócios. Assim sendo, a Compliance 360º ajudará a sua empresa a estabelecer Mecanismos de Integridade e Sistemas de Compliance de treinamento robusto, consistente e efetivo.', name_path: 'efectividade_dos_processos'},
{name: 'Efetividade dos Processos de Compliance', description: 'Se um processo está estabelecido numa empresa, pressupõe-se a existência de sua utilidade. Todavia, no cotidiano, é comum os processos serem executados sem monitoramento sistêmico, que apure o seu desempenho e/ou sua adequação. A Compliance 360º avalia a gama dos processos de Compliance numa organização e propõe medidas, para verificar a efetividade de cada um deles e assegurar que os requisitos estão sendo atendidos.', name_path: 'avaliacao_risco_compliance'},
{name: 'Investigação e Reporte', description: 'Uma empresa interessada em ser íntegra, obriga-se a apurar todas as alegações, denúncias e/ou suspeitas de ilicitudes ou desvios de conduta na organização ou na relação com atores externos (clientes, fornecedores, parceiros, agentes públicos, entre outros). A Compliance 360º oferece toda sua experiência e capacitação para sua empresa executar com sucesso todas as etapas da investigação (desde a identificação de eventual desvio, a apuração em si, o tratamento dos resultados e a implementação de medidas, tanto as disciplinares quanto as dedicadas na prevenção de novas ocorrências similares.', name_path: 'investigacao_e_reporte'},
{name: 'Due Diligence', description: 'A experiência mostra que a grande maioria dos casos de corrupção envolve terceiros, razão pela qual, a gestão eficiente deste relacionamento se torna condição obrigatória para as empresas. A Due Diligence de Integridade (DDI) é incentivada por autoridades de diversos países, pois configura-se como fator relevante para mitigar os respectivos riscos. A DDI tem o propósito de identificar fatos ou indícios incoerentes com a ética e integridade, os quais podem expor a contratante a riscos dos mais variados.', name_path: 'due_diligence'},
{name: 'Compliance Assessment', description: 'Metodologia totalmente inovadora desenvolvida pela Compliance 360º com o objetivo de avaliar o Mecanismo de Integridade e Compliance existente na sua empresa, à luz da Lei 12.846/13 e o Decreto 8.420/15 que a regulamentou, bem como à FCPA e às melhores práticas de mercado, com foco na efetividade de seus processos e elementos. Também são alvo dessa avaliação os mecanismos de Governança da empresa. Como consequência, são confrontadas as expectativas de cada tópico de avaliação com as eventuais lacunas identificadas, resultando numa proposta de plano de ação.', name_path: 'compliance_assessment'},
{name: 'Compliance na Área de Suprimentos', description: 'Na Área de Suprimentos, pela natureza de seus processos, encontra-se grande incidência de fraudes, conflitos de interesse, corrupção e outros desvios, que podem comprometer a imagem da empresa, trazer prejuízos financeiros significativos, além de outras perdas. Por isso, a Compliance 360º desenvolveu um processo estruturado para esta área, combinando treinamento, sensibilização, identificação de riscos específicos no relacionamento com fornecedores, parceiros e terceiros, definição de medidas mitigadoras e estabelecimento de um mecanismo para identificar pistas de eventuais desvios de conduta.', name_path: 'compliance_na_area_de_suprimentos'}, 
{name: 'Apoio ao Comitê de Ética e/ou na Definição das Medidas Disciplinares', description: 'A atuação da Comissão de Ética e a definição de medidas disciplinares configuram-se em aspectos críticos e sensíveis no funcionamento de um Mecanismo de Integridade e Compliance. O acerto das decisões e a forma na condução desses processos estão intimamente ligados à experiência adquirida e aos longos anos de vivência dos profissionais envolvidos na interação com assuntos do gênero. Mas, como conseguir isso quando o Mecanismo de Integridade é recente na empresa? A questão persiste, até mesmo quando o mecanismo já é mais maduro e, por alguma razão, a empresa não conta, no momento, com profissionais com a devida experiência.', name_path: 'apoio_ao_comite_etica'},
{name: 'Coaching ao Compliance Officer', description: 'O sucesso de um Mecanismo de Integridade e Compliance está intimamente condicionado ao sucesso do Compliance Officer, que só será alcançado se este for um profissional com perfil adequado e com experiência no assunto. Obviamente, como o tema Compliance é muito recente no país, a escassez de profissionais com esses requisitos é uma realidade.', name_path: 'coaching_ao_compliance_officer'}])

  ProductComunication.create!([{name: 'Compliance Alerta', description: 'Os Compliance Alertas são e-mails textuais com conteúdos chave para a manutenção do Mecanismo de Integridade e Sistema de Compliance e do compromisso com a conformidade. Assuntos como confidencialidade, concorrentes/antitruste, Lei 12.846/13, entre diversos outros, são tratados com diferentes periodicidades, de acordo com a criticidade, de forma simples, direta e de rápida leitura, com a finalidade de manter o público sempre interessado.', name_path: 'compliance_alerta'},
  {name: 'O Que Você Faria?', description: 'Em formato de quiz, aborda os aspectos mais importantes do Mecanismo de Integridade e Compliance, sendo realizado por meio de diversos vídeos curtos que apresentam, de forma divertida e instrutiva, variados dilemas éticos.', name_path: 'o_que_voce_faria'},
  {name: 'Compliance em Quadrinhos', description: 'O Compliance em Quadrinhos propõe uma abordagem diferenciada e sutil à sensibilização dos leitores para que ajam com ética e integridade. Assim, as histórias apresentam personagens fictícios e que relatam situações comuns do cotidiano.', name_path: 'compliance_em_quadrinhos'},
  {name: 'Reuniões Gerenciais', description: 'Para Campanha Padrão sobre a comunicação do Mecanismo de Integridade e Compliance, disponibilizamos um catálogo com diversas peças de comunicação prontas, criadas sob possibilidade de customização com aplicação da marca de sua empresa. Adquirindo o “Pack Comunicação”, você pode selecionar até 3 (três) peças de acordo com o seu interesse e forneceremos as matrizes, para você providenciar a produção, sem gastar energia na elaboração, desenvolvimento de modelos, etc. Se desejar adquirir mais peças, consulte a Compliance Total.', name_path: 'reunioes_gerenciais'},
  {name: 'Comunicação Externa', description: 'Instruir, qualificar e treinar as pessoas consiste em condição obrigatória para a formação de profissionais aptos para o exercício de suas funções. Da mesma maneira, para o Compliance, os treinamentos cumprirão tal papel e, juntamente com a comunicação regular, esclarecerão os riscos à empresa e aos funcionários, propiciando a estes a opção de fazer a “escolha certa”, tanto em relação a suas atitudes, quanto na realização dos processos e consecução dos negócios. Assim sendo, a Compliance 360º ajudará a sua empresa a estabelecer Mecanismos de Integridade e Sistemas de Compliance de treinamento robusto, consistente e efetivo.', name_path: 'comunicacao_externa'},
  {name: 'Plano de Comunicação', description: 'Uma empresa interessada em ser íntegra, obriga-se a apurar todas as alegações, denúncias e/ou suspeitas de ilicitudes ou desvios de conduta na organização ou na relação com atores externos (clientes, fornecedores, parceiros, agentes públicos, entre outros). A Compliance 360º oferece toda sua experiência e capacitação para sua empresa executar com sucesso todas as etapas da investigação (desde a identificação de eventual desvio, a apuração em si, o tratamento dos resultados e a implementação de medidas, tanto as disciplinares quanto as dedicadas na prevenção de novas ocorrências similares.', name_path: 'plano_de_comunicacao'},
  {name: 'Due Diligence', description: 'A experiência mostra que a grande maioria dos casos de corrupção envolve terceiros, razão pela qual, a gestão eficiente deste relacionamento se torna condição obrigatória para as empresas. A Due Diligence de Integridade (DDI) é incentivada por autoridades de diversos países, pois configura-se como fator relevante para mitigar os respectivos riscos. A DDI tem o propósito de identificar fatos ou indícios incoerentes com a ética e integridade, os quais podem expor a contratante a riscos dos mais variados.', name_path: 'due_diligence'}])

  ProductTrainner.create!([{name: 'Compliance EAD', description: 'Oferecemos ao cliente uma plataforma própria EAD (educação à distância), para veiculação de treinamentos em vídeo aos seus colaboradores. São diversos módulos prontos, contendo os principais assuntos para sensibilização da ética, integridade e Compliance, tais como: canal de denúncia, comitês de ética, investigação, conflito de interesses, lavagem de dinheiro, antitruste, entre outros. O cliente pode solicitar o desenvolvimento de novos temas e, se desejar, pode inclusive sugerir conteúdos.', name_path: 'compliance_ead'},
    {name: 'Kit Gestor', description: 'Uma prática voltada para a sensibilização e comprometimento de gerentes e líderes, por meio da condução de reuniões diretamente com suas equipes, buscando a capilarização do Compliance em toda a empresa. Essa solução reforça o comprometimento e o apoio do “middle management” ao Mecanismo de Integridade e Compliance.', name_path: 'kit_gestor'},
    {name: 'Treinamentos Presenciais', description: 'Nossos treinamentos presenciais são elaborados de forma a abranger as questões mais importantes para o Compliance: corrupção, cartel, antitruste, fraude, políticas internas e procedimentos, código de conduta, canal de denúncias e todos os demais elementos de um Mecanismo de Integridade e Compliance.', name_path: 'treinamentos_presenciais'},
    {name: 'Train the Trainer', description: 'Trata-se do material para o Compliance Officer ministrar cursos de capacitação para candidatos a instrutores, que serão responsáveis por replicar treinamentos presenciais na empresa. Este recebe também instruções prévias de como usar o material e definir o público que deve participar desse curso.', name_path: 'train_the_trainer'},
    {name: 'Plano de Treinamentos', description: 'O Plano de Treinamento abrange todos os produtos do Pack Treinamento e é oferecido gratuitamente para quem adquirir o pacote completo. Apresenta a vantagem de integração dos temas e o usuário aproveita a arquitetura do conjunto, pois o conteúdo de cada produto foi planejado de modo a abordar os assuntos mais importantes e na frequência adequada para uma excelente disseminação. Se o cliente adquirir os pacotes Treinamento e Comunicação, terá, assim, um Plano completo para comunicar, treinar, qualificar e sensibilizar os funcionários.', name_path: 'plano_de_treinamentos'}])
  
    ProductTecnology.create!([{name: 'Compliance Assessment Online', description: 'Versão simplificada do Compliance Assessment, porém, capaz de cobrir os aspectos mais importantes e assegurar uma avaliação abrangente e eficaz do Mecanismo de Integridade.', name_path: 'compliance_assessment_online'},
      {name: 'Business Partners', description: 'Ferramenta para a gestão de parceiros de negócio, abrangendo as questões mais relevantes para o Mecanismo de Integridade. Dentre algumas de suas funcionalidades estão workflow das aprovações, classificação automática de riscos, controle de validade de due diligences e listas de documentos necessários para cadastro de acordo com o perfil do parceiro.', name_path: 'business_partners'},
      {name: 'Anti Retaliation Tool', description: 'Usualmente, as empresas estabelecem em seus Códigos de Conduta a proibição de retaliação, mas, na prática, não possuem nenhum mecanismo para evita-la. Além disso, há situações que podem comprometer significativamente o Compliance na organização, tais como: a) desligamento (voluntário ou demissão) de um denunciante, envolvido ou testemunha numa investigação em curso; b) promoção ou transferência de pessoas (novos cargos, outras cidades ou outros países) às vésperas da aplicação de uma medida disciplinar. A Anti Retaliation Tool é uma ferramenta inovadora, de simples uso na empresa e muito eficiente na solução desses problemas.', name_path: 'anti_retaliation_tool'},
      {name: 'Integrity Plus', description: 'I-Plus, ferramenta inovadora para assegurar a efetividade da comunicação e treinamento, além de diversas outras funcionalidades, com interação a aplicativos móveis.', name_path: 'integrity_plus'}])
    
      ProductManagement.create!([{name: 'Kit Gestão de Riscos', description: 'Esse kit fornece uma metodologia para a identificação dos riscos de Compliance, incluindo uma lista dos principais e suas respectivas medidas mitigadoras que, se implementadas, formam um Mecanismo de Integridade e Compliance com todos os ingredientes para manter-se efetivo.', name_path: 'kit_gestao_de_riscos'},
        {name: 'Kit Perfis Profissionais', description: 'Assim, o Kit Perfis Profissionais foi desenvolvido para ajudar as organizações vencerem rapidamente esses desafios. Ele contém os requisitos básicos para um profissional desempenhar bem suas funções dentro da organização de Compliance, servindo de base para o recrutamento de pessoas e/ou acompanhamento de seus desempenhos.', name_path: 'kit_perfis_profissionais'},
        {name: 'Kit Documentação', description: 'A Compliance Total desenvolveu, então, o Kit Documentação, para atender às necessidades de seus clientes. Esse kit é composto por um conjunto de documentos elaborados para o pleno atendimento das leis, decretos, guidelines e normas relativas ao assunto, tais como DSC 10.000 (Diretrizes para o Sistema de Compliance) e ISO 37.001 (Norma Antissuborno).', name_path: 'kit_documentacao'},
        {name: 'Sistema de Pesquisas', description: 'Medir a efetividade de determinados processos de Compliance consiste em dificuldade generalizada entre as empresas. Também não é tarefa simples estabelecer rotinas de pesquisas sobre Compliance com a frequência necessária, sem, contudo, saturar a organização.', name_path: 'sistema_de_pesquisas'},
        {name: 'Gestão do Desempenho', description: 'Pensando nisso, a Compliance Total desenvolveu uma sistemática que prevê a análise crítica pela Alta Direção da empresa, cujo foco é apurar o desempenho dos principais processos do Compliance. São previstas reuniões trimestrais e, para elas, são fornecidas pautas dos assuntos a serem tratados.', name_path: 'gestao_do_desempenho'},
        {name: 'Gestão dos Embaixadores', description: 'Para vencer essas dificuldades, a Compliance Total sugere a adoção de um conceito testado e aprovado em diversas empresas: o uso dos Embaixadores. Com ele, obtém-se a melhor relação custo x benefício no estabelecimento de sua organização e estrutura de Compliance.', name_path: 'gestao_dos_embaixadores'}])
      
    